// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj40uZEeECYfXiE70-BE28EU-bHDJT1y8',
    appId: '1:471245254584:web:228a8d54a594c6ee1aa94d',
    messagingSenderId: '471245254584',
    projectId: 'fintak-3ba47',
    authDomain: 'fintak-3ba47.firebaseapp.com',
    storageBucket: 'fintak-3ba47.firebasestorage.app',
    measurementId: 'G-NBF7GEDWYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHu5Mucfsehjn34aWmUAY6O71u6io7fE4',
    appId: '1:471245254584:android:bac7cac0c78df6801aa94d',
    messagingSenderId: '471245254584',
    projectId: 'fintak-3ba47',
    storageBucket: 'fintak-3ba47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdS0uEEqBu_yQWSHxOI1F6TMHS1iHCxYo',
    appId: '1:471245254584:ios:10d7d7dbcbb7f8791aa94d',
    messagingSenderId: '471245254584',
    projectId: 'fintak-3ba47',
    storageBucket: 'fintak-3ba47.firebasestorage.app',
    iosBundleId: 'com.example.fintak',
  );
}
